### ISSUE TITLE
Installation Metadata is Incorrect

### ISSUE THREAD

**Issue by youvegotwq** [shouhu21/sn-theme-horizon-dark#1]
Hello!

I've noticed that the installation metadata at `https://listed.to/p/U1asXPAO9k` is incorrect and causes installation issues. After looking, it has to do with the **identifier** attribute in the JSON as that is used to create the folder for resources when installing the theme.

For reference, the _identifier_ attribute right now is `https://github.com/shouhu21/sn-theme-horizon-dark`. Windows cannot have folders with a colon or slashes in the name, so installing the theme results in an error. I've edited the _identifier_ attribute to `org.github.shouhu21.sn-theme-horizon-dark` and tested installation, and everything installs correctly again. For reference, my hosted JSON for that is at `https://listed.to/p/qg4NMQB9KM`.

I was going to submit a pull request for the change, but realized that this JSON isn't actually in the repo, so wanted to submit an issue for reference.

Thanks!

**Comment by luisstd** [comment]
Thank you very much! I was aware of the issue with Windows but I haven't been able to find a solution for it so far. I'm glad you figured it out, I have updated the JSON for both versions of the theme. Now the theme should install correctly on all platforms.
