### ISSUE TITLE
Note highlighting color is not appearing as it should be

### ISSUE THREAD

**Issue by stripedgoat** [shouhu21/sn-theme-horizon-dark#2]
Hello. I've just installed this theme, and the highlighting color for notes is not looking good. It applies for both the web app of Standard Notes, and the macOS Standard Notes app as well.

![Screen Shot 2022-03-05 at 6 04 01 PM](https://user-images.githubusercontent.com/99847783/156893084-2111634a-73fd-4158-8a09-1f34ebc4567a.jpg)

I also tried opening a new account for Standard Notes, but it did not solve it.

I noticed this exact same bug appearing with the 3rd-party Dracula theme as well.... Though not all 3rd-party themes have this problem... For example, the "Gruvbox Dark Theme" is appearing properly (but that theme doesn't utilize any hover highlighting color).

Is this a problem that appears only for me? It really is frustrating... 😩
Hope you can help 🙏🏼

Thanks!

**Comment by luisstd** [comment]
Thanks for letting me know! I can reproduce the bug and I will try to fix it as soon as I can :)

**Comment by stripedgoat** [comment]
> Thanks for letting me know! I can reproduce the bug and I will try to fix it as soon as I can :)

Thank you!
