### ISSUE TITLE
Left panel active selection colour too bright

### ISSUE THREAD

**Issue by CapitolRadio** [shouhu21/sn-theme-horizon-dark#4]
When selecting tag/view on the left panel the active selection colour is a bright white and does not match the theme
![image](https://user-images.githubusercontent.com/54081978/197531841-1ea876c9-d0c2-4ae4-86d2-390cf3c41c70.png)

**Comment by luisstd** [comment]
Thanks for pointing out the issue! Should be fixed now :)

**Comment by CapitolRadio** [comment]
Looks great, thanks a lot!
